FROM node:14-alpine

RUN apk add vim --update --no-cache --quiet
RUN apk add bash --update --no-cache --quiet
RUN apk add npm --update --no-cache --quiet
RUN apk add python3 --update --no-cache --quiet && ln -sf python3 /usr/bin/python
RUN npm install -g firebase-tools

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

CMD [ "bash" ]

